---
- name: 'get package'
  uri: 
    url: "{{ zoo_link }}"
    method: POST
    dest: /opt

- name: 'unpack'
  unarchive:
    src: /opt/{{ zoo_version }}.tar.gz
    dest: /opt/
    remote_src: yes

- name: 'install configure'
  shell: |
    mv /opt/{{ zoo_version }} /opt/zookeeper
    useradd -c "zookeeper user" -r -s /bin/false zookeeper
    mkdir -p /var/log/zookeeper
    mkdir -p /var/zookeeper
    chown -R zookeeper:zookeeper /var/zookeeper
    chown -R zookeeper:zookeeper /var/log/zookeeper
    chown -R zookeeper:zookeeper /opt/zookeeper
    echo '{{ zoo_id }}' > /var/zookeeper/myid
    rm -rf /opt/{{ zoo_version }}.tar.gz
    rm -rf /opt/{{ zoo_version }}
    sed -i 's|ZOO_LOG_DIR="."|ZOO_LOG_DIR="/var/log/zookeeper"|g' /opt/zookeeper/bin/zkEnv.sh

- name: 'copy zoo.cfg'
  template:
    src: "zoo.cfg.j2"
    dest: "/opt/zookeeper/conf/zoo.cfg"
    owner: "zookeeper"
    group: "zookeeper"
    mode: 0644

- name: 'copy zoo service'
  copy:
    src: "zookeeper.service"
    dest: "/etc/systemd/system/"

- name: 'run zoo'
  shell: |
    systemctl daemon-reload
    systemctl enable zookeeper
    systemctl start zookeeper